export const clientFormFields = {
  client: {
    title: 'Клиент',
    required: true,
    type: 'text',
    maxLength: 255,
    placeholder: 'Фамилия Имя Отчество',
    icon: '',
    link: '',
  },
  phone: {
    title: 'Телефон',
    required: false,
    type: 'tel',
    maxLength: 255,
    placeholder: '',
    icon: 'phone',
    link: 'tel:',
  },
  email: {
    title: 'E-mail',
    required: false,
    type: 'email',
    maxLength: 11,
    placeholder: '',
    icon: 'mail',
    link: 'mailto:',
  },
  telegram: {
    title: 'Telegram',
    required: false,
    type: 'text',
    maxLength: 255,
    placeholder: 'Телеграм',
    icon: 'telegram',
    link: '',
  },
  whatsApp: {
    title: 'Whatsapp',
    required: false,
    type: 'text',
    maxLength: 11,
    placeholder: 'Whatsapp',
    icon: 'wa',
    link: '',
  },
}
